// frontend_react/src/components/Header/Header.jsx
// import React from 'react';
// import { Link, NavLink } from 'react-router-dom';
// import './Header.css';

// const Header = () => {
//     return (
//         <header className="header fixed-top shadow-sm">
//             <div className="container-fluid">
//                 <div className="d-flex justify-content-between align-items-center p-3">
//                     {/* Logo or App Name */}
//                     <Link to="/home" className="text-color fw-bold h2 mb-0 ms-3">
//                         <img src="/assets/logo_2.png" alt="Logo" className="logo" />
//                     </Link>

//                     {/* Navigation Links */}
//                     <nav>
//                         <ul className="nav me-5">
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Home
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/instalaciones" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Instalaciones
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/Servicios" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Servicios
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-4">
//                                 <NavLink 
//                                     to="/entrenadores" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Entrenadores
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item">
//                                 <NavLink 
//                                     to="/auth" 
//                                     className="nav-link auth fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Unirse al club
//                                 </NavLink>
//                             </li>
//                         </ul>
//                     </nav>
//                 </div>
//             </div>
//         </header>
//     );
// };

// export default Header;
import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import './Header.css';

const Header = () => {
    return (
        <header className="header fixed-top shadow-sm">
            <div className="container-fluid">
                <div className="d-flex justify-content-between align-items-center p-3">
                    {/* Logo or App Name */}
                    <Link to="/home" className="text-color fw-bold h2 mb-0 ms-3">
                        <img src="/assets/logo_2.png" alt="Logo" className="logo" />
                    </Link>

                    {/* Navigation Links */}
                    <nav>
                        <ul className="nav me-5">
                            <li className="nav-item me-3">
                                <NavLink 
                                    exact="true"
                                    to="/" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Home
                                </NavLink>
                            </li>
                            <li className="nav-item me-3">
                                <NavLink 
                                    to="/instalaciones" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Instalaciones
                                </NavLink>
                            </li>
                            <li className="nav-item me-3">
                                <NavLink 
                                    to="/Servicios" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Servicios
                                </NavLink>
                            </li>
                            <li className="nav-item me-4">
                                <NavLink 
                                    to="/entrenadores" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Entrenadores
                                </NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink 
                                    to="/auth" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link auth fw-bold fs-5 isActive" : "nav-link auth fw-bold fs-5"
                                    }
                                >
                                    Unirse al club
                                </NavLink>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    );
};

export default Header;

// frontend/ZenithZone/src/components/Header.vue
<template>
    <header class="header fixed-top shadow-sm">
        <div class="container-fluid">
            <div class="d-flex justify-content-between align-items-center p-3">
                <!-- Logo or App Name -->
                <router-link to="/home" class="text-color fw-bold h2 mb-0 ms-3">
                    <img src="../assets/logo_2.png" alt="" class="logo">
                </router-link>

                <!-- Navigation Links -->
                <nav>
                    <ul class="nav me-5">
                        <li class="nav-item me-3">
                            <router-link to="/home" class="nav-link text-color fw-bold fs-5"
                                active-class="isActive text-black">
                                Home
                            </router-link>
                        </li>
                        <li class="nav-item me-3">
                            <router-link to="/instalaciones" class="nav-link text-color fw-bold fs-5"
                                active-class="isActive text-black">
                                Instalaciones
                            </router-link>
                        </li>
                        <li class="nav-item me-3">
                            <router-link to="/Servicios" class="nav-link text-color fw-bold fs-5"
                                active-class="isActive text-black">
                                Servicios
                            </router-link>
                        </li>
                        <li class="nav-item me-4">
                            <router-link to="/entrenadores" class="nav-link text-color fw-bold fs-5"
                                active-class="isActive text-black">
                                Entrenadores
                            </router-link>
                        </li>
                        <li class="nav-item">
                            <router-link to="/auth" class="nav-link auth fw-bold fs-5"
                                active-class="isActive text-black">
                                Unirse al club
                            </router-link>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</template>

<script>
export default {
    name: "Header",
};
</script>


<style scoped>
.isActive {
    background-color: #ff6600;
    border-radius: 5px;
}

.text-color {
    color: #ff6600;
    transition: all 0.3s;

    &:hover {
        color: white;
    }
}

.auth {
    background-color: white;
    border-radius: 10px;
    color: #ff6600;
    transition: all 0.3s;

    &:hover {
        color: black;
        background-color: #ff6600;
    }
}

.header {
    background-color: rgb(20, 20, 20);
}

.logo {
    max-height: 50px;
    width: auto;
    transition: transform 0.3s;

    &:hover {
        transform: scale(1.1);
    }
}
</style>
