// frontend_react/src/components/Header/Header.jsx
// import React from 'react';
// import { Link, NavLink } from 'react-router-dom';
// import './Header.css';

// const Header = () => {
//     return (
//         <header className="header fixed-top shadow-sm">
//             <div className="container-fluid">
//                 <div className="d-flex justify-content-between align-items-center p-3">
//                     {/* Logo or App Name */}
//                     <Link to="/home" className="text-color fw-bold h2 mb-0 ms-3">
//                         <img src="/assets/logo_2.png" alt="Logo" className="logo" />
//                     </Link>

//                     {/* Navigation Links */}
//                     <nav>
//                         <ul className="nav me-5">
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Home
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/instalaciones" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Instalaciones
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-3">
//                                 <NavLink 
//                                     to="/Servicios" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Servicios
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item me-4">
//                                 <NavLink 
//                                     to="/entrenadores" 
//                                     className="nav-link text-color fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Entrenadores
//                                 </NavLink>
//                             </li>
//                             <li className="nav-item">
//                                 <NavLink 
//                                     to="/auth" 
//                                     className="nav-link auth fw-bold fs-5"
//                                     activeClassName="isActive"
//                                 >
//                                     Unirse al club
//                                 </NavLink>
//                             </li>
//                         </ul>
//                     </nav>
//                 </div>
//             </div>
//         </header>
//     );
// };

// export default Header;
import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import './Header.css';

const Header = () => {
    return (
        <header className="header fixed-top shadow-sm">
            <div className="container-fluid">
                <div className="d-flex justify-content-between align-items-center p-3">
                    {/* Logo or App Name */}
                    <Link to="/home" className="text-color fw-bold h2 mb-0 ms-3">
                        <img src="/assets/logo_2.png" alt="Logo" className="logo" />
                    </Link>

                    {/* Navigation Links */}
                    <nav>
                        <ul className="nav me-5">
                            <li className="nav-item me-3">
                                <NavLink 
                                    exact="true"
                                    to="/" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Home
                                </NavLink>
                            </li>
                            <li className="nav-item me-3">
                                <NavLink 
                                    to="/instalaciones" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Instalaciones
                                </NavLink>
                            </li>
                            <li className="nav-item me-3">
                                <NavLink 
                                    to="/Servicios" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Servicios
                                </NavLink>
                            </li>
                            <li className="nav-item me-4">
                                <NavLink 
                                    to="/entrenadores" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link text-color fw-bold fs-5 isActive" : "nav-link text-color fw-bold fs-5"
                                    }
                                >
                                    Entrenadores
                                </NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink 
                                    to="/auth" 
                                    className={({ isActive }) => 
                                        isActive ? "nav-link auth fw-bold fs-5 isActive" : "nav-link auth fw-bold fs-5"
                                    }
                                >
                                    Unirse al club
                                </NavLink>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    );
};

export default Header;

// frontend/ZenithZone/src/components/shared/Header.vue
<template>
    <header class="header fixed-top shadow-sm">
        <div class="container-fluid">
            <div class="d-flex justify-content-between align-items-center p-3">
                <!-- Logo or App Name -->
                <div class="text-color fw-bold h2 mb-0 ms-3" @click="redirects.home">
                    <img src="/assets/logo_2.png" alt="Logo" class="logo">
                </div>

                <!-- Navigation Links -->
                <nav>
                    <ul class="nav me-5">
                        <li class="nav-item me-3">
                            <a @click="redirects.home" class="nav-link text-color fw-bold fs-5" 
                                :class="{ isActive: isHome }">
                                Home
                            </a>
                        </li>
                        <li class="nav-item me-3">
                            <a @click="redirects.instalaciones" class="nav-link text-color fw-bold fs-5" 
                                :class="{ isActive: isInstalaciones }">
                                Instalaciones
                            </a>
                        </li>
                        <li class="nav-item me-3">
                            <a @click="redirects.servicios" class="nav-link text-color fw-bold fs-5" 
                                :class="{ isActive: isServicios }">
                                Servicios
                            </a>
                        </li>
                        <li class="nav-item me-4">
                            <a @click="redirects.entrenadores" class="nav-link text-color fw-bold fs-5" 
                                :class="{ isActive: isEntrenadores }">
                                Entrenadores
                            </a>
                        </li>
                        <li v-if="!state.isLogged" class="nav-item">
                            <a @click="redirects.login" class="nav-link auth fw-bold fs-5" 
                                :class="{ isActive: isLogin }">
                                Unirse al club
                            </a>
                        </li>
                        <li v-if="state.isLogged" class="nav-item">
                            <a @click="logout" class="nav-link auth fw-bold fs-5">
                                Cerrar sesión
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</template>


<script>
import Constant from '@/Constant';
import { computed } from 'vue';
import { reactive } from 'vue';
import { useRouter } from 'vue-router';
import { useStore } from 'vuex';

export default {
    name: "Header",

    computed: {
        isHome() {
            return this.$route.name === 'home';
        },
        isInstalaciones() {
            return this.$route.name === 'instalaciones';
        },
        isServicios() {
            return this.$route.path.startsWith('/servicios');
        },
        isEntrenadores() {
            return this.$route.name === 'entrenadores';
        },
        isLogin() {
            return ['/login', '/register'].includes(this.$route.path);
        },
    },

    setup() {
        const router = useRouter();
        const store = useStore();

        const redirects = {
            home: () => router.push({ name: 'home' }),
            instalaciones: () => router.push({ name: 'instalaciones' }),
            servicios: () => router.push({ name: 'serviciosEntrenamientos' }),
            entrenadores: () => router.push({ name: 'entrenadores' }),
            login: () => router.push({ name: 'login' })
        };

        const state = reactive({
            profile: computed(() => store.getters['user/GetProfile']),
            isAdmin: computed(() => store.getters['user/GetIsAdmin']),
            isEntrenador: computed(() => store.getters['user/GetIsEntrenador']),
            isLogged: computed(() => store.getters['user/GetIsLogged']),
        });

        const logout = () => {
            store.dispatch(`user/${Constant.LOGOUT}`);
            router.push({ name: 'home' });
        };

        return { redirects, state, logout };
    }
};
</script>


<style scoped>
.isActive {
    background-color: #ff6600;
    color: black;
    border-radius: 5px;
}

.text-color {
    color: #ff6600;
    transition: all 0.3s;

    &:hover {
        color: white;
    }
}

.auth {
    background-color: white;
    border-radius: 10px;
    color: #ff6600;
    transition: all 0.3s;

    &:hover {
        color: black;
        background-color: #ff6600;
    }
}

.header {
    background-color: rgb(20, 20, 20);
}

.logo {
    max-height: 50px;
    width: auto;
    transition: transform 0.3s;
    cursor: pointer;

    &:hover {
        transform: scale(1.1);
    }
}

.nav-link.isActive {
    color: #000;
}
</style>
