// frontend/ZenithZone/src/views/client/Home.vue
<template>
    <HeroSection />
    
    <MiddleSection />
    <Olympics />
    <GraphicSection style="margin-top: 150px;"/>
    <ListDeportesHome />
</template>

<script>
import Olympics from '../../components/home/Olympics.vue';
import HeroSection from '../../components/home/HeroSection.vue';
import MiddleSection from '@/components/home/MiddleSection.vue';
import GraphicSection from '@/components/home/GraphicSection.vue';
import ListDeportesHome from '@/components/home/ListDeportesHome.vue';

export default {
    components: {
        HeroSection,
        MiddleSection,
        Olympics,
        GraphicSection,
        ListDeportesHome
    }
};
</script>

<style scoped>
    body {
        margin-top: 87px;
        background-color: rgb(245, 245, 245);
        font-family: 'Roboto', sans-serif;
    }
</style>

// frontend_react/src/components/Home/Home.jsx
import React from 'react';
import ListDeportesHome from './ListDeportesHome/ListDeportesHome';
import PistaList from './PistaList';
import MiddleSection from './MiddleSection/MiddleSection';
import HeroSection from './HeroSection/HeroSection';
import Olympics from './Olympics/Olympics';
import GraphicSection from './GraphicSection/GraphicSection';
import './Home.css';
const Home = () => {
    return (
        <> 
        <HeroSection />     
        <MiddleSection />
        <Olympics />
        <GraphicSection />
        <ListDeportesHome /> 
        </>
    );
};

export default Home;
