// frontend_react/src/components/Home/GraphicSection/Graphics.jsx
import React, { useRef, useEffect } from 'react';
import { Chart, registerables } from 'chart.js';
import './Graphics.css';


Chart.register(...registerables);

const Graphics = () => {
  const radarChart = useRef(null);

  useEffect(() => {

    const ctx = radarChart.current.getContext('2d');
    if (ctx) {

      if (radarChart.current.chart) {
        radarChart.current.chart.destroy();
      }

      const chart = new Chart(ctx, {
        type: 'radar',
        data: {
          labels: ['Motivación', 'Agilidad', 'Velocidad', 'Aguante', 'Fuerza'],
          datasets: [
            {
              data: [90, 70, 90, 43, 56],
              borderColor: 'rgba(255, 162, 80, 1)',
              backgroundColor: 'rgba(255, 162, 80, 0.2)',
              borderWidth: 2,
            },
            {
              data: [40, 40, 50, 73, 96],
              borderColor: 'rgba(55, 162, 80, 1)',
              backgroundColor: 'rgba(55, 162, 80, 0.2)',
              borderWidth: 2,
            },
          ],
        },
        options: {
          responsive: true,
          plugins: {
            legend: {
              display: false,
            },
          },
          scales: {
            r: {
              angleLines: {
                color: 'rgba(0, 0, 0, 0.3)',
              },
              suggestedMin: 0,
              suggestedMax: 100,
              ticks: {
                stepSize: 20,
                font: {
                  size: 14,
                },
                color: '#4b5563',
              },
              grid: {
                color: 'rgba(0, 0, 0, 0.1)',
              },
              pointLabels: {
                font: {
                  size: 20,
                },
                color: '#000',
              },
            },
          },
        },
      });

      // Guardamos la instancia del gráfico en la referencia del canvas
      radarChart.current.chart = chart;
    }

    // Cleanup (limpieza): destruir el gráfico al desmontar el componente
    return () => {
      if (radarChart.current.chart) {
        radarChart.current.chart.destroy();
      }
    };
  }, []); // Solo se ejecuta una vez al montar el componente

  return (
    <div className="mt-5 container-graphics">
      <canvas ref={radarChart}></canvas>
    </div>
  );
};

export default Graphics;

// frontend/ZenithZone/src/components/home/Graphics.vue
<template>
<div class="mt-5">
    <canvas ref="radarChart"></canvas>
</div>
</template>


<script>
import {
    Chart,
    registerables
} from 'chart.js';
import {
    onMounted,
    ref
} from 'vue';

Chart.register(...registerables);

export default {
    name: 'RadarChart',
    setup() {
        const radarChart = ref(null);

        onMounted(() => {
            const ctx = radarChart.value.getContext('2d');

            radarChart.value.width = 600;
            radarChart.value.height = 600;

            new Chart(ctx, {
                type: 'radar',
                data: {
                    labels: ['Motivación', 'Agilidad', 'Velocidad', 'Aguante', 'Fuerza',],
                    datasets: [{
                            data: [90, 70, 90, 43, 56],
                            borderColor: 'rgba(255, 162, 80, 1)', // Azul
                            backgroundColor: 'rgba(255, 162, 80, 0.2)', // Transparencia
                            borderWidth: 2,
                        },
                    ],
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            display: false
                        },
                    },
                    scales: {
                        r: {
                            angleLines: {
                                color: 'rgba(0, 0, 0, 0.3)', // Líneas de los ejes
                            },
                            suggestedMin: 0, // Mínimo sugerido
                            suggestedMax: 100, // Máximo sugerido
                            ticks: {
                                stepSize: 20, // Intervalo de valores
                                font: {
                                    size: 14,
                                },
                                color: '#4b5563', // Color del texto
                            },
                            grid: {
                                color: 'rgba(0, 0, 0, 0.1)', // Líneas de la cuadrícula
                            },
                            pointLabels: {
                                font: {
                                    size: 20,
                                },
                                color: '#000', // Color de las etiquetas (ejes)
                            },
                        },
                    },
                },
            });
        });

        return {
            radarChart,
        };
    },
};
</script>

  
<style>
canvas {
    max-width: 700px;
    height: auto;
    margin: auto;
    /* margin-right: 10; */
}
</style>
