// frontend_react/src/components/Home/ListDeportesHome/ListDeportesHome.jsx
import React, { useEffect, useState } from 'react';
import CardDeportes from './CardDeportes/CardDeportes'; 
import { getDeportes } from '../../../services/GetDeportes'; 
import './ListDeportesHome.css';

const ListDeportesHome = () => {
    const [deportes, setDeportes] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        
        const fetchDeportes = async () => {
            const { data, loading } = await getDeportes();
            setDeportes(data);
            setLoading(loading);
        };

        fetchDeportes();
    }, []);
    if (loading) return <p>Loading...</p>;

    return (
        <main className="body-deportes-home">
            <div className="test">
                <div className="test-2">
                    <p className="text-center text-white text-deportes fst-italic mb-0">
                        LOS DEPORTES DE LA ÉLITE
                    </p>
                </div>  
            </div>        
            <div className="row justify-content-center">
                {deportes.slice(0, 8).map((deporte) => (
                    <CardDeportes key={deporte.id} deporte={deporte} className="col-md-3" />
                ))}
            </div>
        </main>
    );
};

export default ListDeportesHome;

// frontend/ZenithZone/src/components/home/ListDeportesHome.vue
<template>
    <main class="body-deportes-home">
        <div class="test">
            <div class="test-2">
                <p class="text-center text-white text-deportes fst-italic mb-0">LOS DEPORTES DE LA ÉLITE</p>
            </div>  
        </div>        
        <div class="row justify-content-center">
            <CardDeportes v-for="deporte in state.deportes.slice(0,8)" :key="deporte.id" :deporte="deporte" class="col-md-3" />
        </div>
    </main>

</template>

<script>
import { reactive, computed, onMounted } from 'vue';
import { useStore } from 'vuex';
import Constant from '../../Constant';
import CardDeportes from './CardDeportesHome.vue';

export default {
    components: {
        CardDeportes
    },
    setup() {
        const store = useStore();

        store.dispatch(`deportes/${Constant.INITIALIZE_DEPORTE}`);

        const state = reactive({
            deportes: computed(() => store.getters['deportes/GetDeportes'])
        });

        return { state };
    }
};
</script>

<style scoped>
.body-deportes-home{
    background-color: rgb(20, 20, 20);
}

.test {
    /* box-shadow: inset 20px 20px 0 15px #ff6600; */
    box-shadow: inset -20px -20px 0 15px rgba(0, 255, 229, 0.9);
}

.test-2 {
    /* box-shadow: inset -20px -20px 0 15px rgba(0, 255, 229, 0.9); */
    box-shadow: inset 20px 20px 0 15px #ff6600;
}

.text-deportes{
    padding: 70px;
    font-size: 60px;
    font-family: 'Roboto', sans-serif;
    text-shadow: 5px 3px 1px #ff6600;
}

.deportes-list {
    display: flex;
    flex-wrap: wrap;
}

.col-md-3 {
    margin: 0px;
    padding: 0;
}

.row{
    margin: 0;
    padding: 0;
}
</style>
