// frontend_react/src/components/Home/MiddleSection/MiddleSection.jsx
import React, { useEffect, useState } from 'react';
import { Splide, SplideSlide } from '@splidejs/react-splide';
import '@splidejs/splide/dist/css/splide.min.css';
import './MiddleSection.css';


const MiddleSection = () => {
    const [pistas, setPistas] = useState([]);

    useEffect(() => {
       
        const fetchPistas = async () => {   
            const data = [
                { id: 1, image: 'pista_atletismo.jpg' },
                { id: 2, image: 'piscina.jpg' },
                { id: 3, image: 'pista_ciclismo.jpg' },
                { id: 4, image: 'rocodromo.jpg' },
                { id: 5, image: 'pista_padel.jpg' },
            ];
            setPistas(data);
        };

        fetchPistas();
    }, []);

    const splideOptions = {
        type: 'loop',
        autoplay: true,
        interval: 3000,
        height: '100%',
        arrows: false,
        pagination: true,
    };
    return (
        <div className="landing-section d-flex">
            {/* Text Section */}
            <div className="text-section col-md-6 d-flex flex-column justify-content-center px-4">
                <div className="text-container">
                    <p className="fw-bold text-center">
                        LAS MEJORES INSTALACIONES
                    </p>
                </div>
            </div>

            {/* Carousel Section */}
            <div className="carousel-section col-md-6 p-0">
                <Splide options={splideOptions} className="h-100">
                    {pistas.length > 0 ? (
                        pistas.map((pista) => (
                            <SplideSlide key={pista.id}>
                                <img
                                    src={`/assets/home/${pista.image}`}
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt=""
                                />
                            </SplideSlide>
                        ))
                    ) : (
                        <>
                            <SplideSlide>
                                <img
                                    src="/assets/home/pista_atletismo.jpg"
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt="Pista de Atletismo"
                                />
                            </SplideSlide>
                            <SplideSlide>
                                <img
                                    src="/assets/home/piscina.jpg"
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt="Piscina"
                                />
                            </SplideSlide>
                            <SplideSlide>
                                <img
                                    src="/assets/home/pista_ciclismo.jpg"
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt="Pista de Ciclismo"
                                />
                            </SplideSlide>
                            <SplideSlide>
                                <img
                                    src="/assets/home/rocodromo.jpg"
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt="Rocódromo"
                                />
                            </SplideSlide>
                            <SplideSlide>
                                <img
                                    src="/assets/home/pista_padel.jpg"
                                    className="d-block w-100 h-100 object-fit-cover"
                                    alt="Pista de Pádel"
                                />
                            </SplideSlide>
                        </>
                    )}
                </Splide>
            </div>
        </div>
    );
};

export default MiddleSection;

// frontend/ZenithZone/src/components/home/MiddleSection.vue
<template>
<div class="landing-section d-flex">
    <!-- Sección del texto -->
    <div class="text-section col-md-6 d-flex flex-column justify-content-center px-4">
        <div class="text-container">
            <p class="fw-bold text-center">
                LAS MEJORES INSTALACIONES
            </p>
        </div>
    </div>

    <!-- Sección del carrusel -->
    <div class="carousel-section col-md-6 p-0">
        <Splide :options="splideOptions" class="h-100">
            <SplideSlide>
                <img src="../../assets/home/pista_atletismo.jpg" class="d-block w-100 h-100 object-fit-cover" alt="Imagen 1" />
            </SplideSlide>
            <SplideSlide>
                <img src="../../assets/home/pista_ciclismo.jpg" class="d-block w-100 h-100 object-fit-cover" alt="Imagen 2" />
            </SplideSlide>
            <SplideSlide>
                <img src="../../assets/home/piscina.jpg" class="d-block w-100 h-100 object-fit-cover" alt="Imagen 3" />
            </SplideSlide>
            <SplideSlide>
                <img src="../../assets/home/rocodromo.jpg" class="d-block w-100 h-100 object-fit-cover" alt="Imagen 3" />
            </SplideSlide>
            <SplideSlide>
                <img src="../../assets/home/pista_padel.jpg" class="d-block w-100 h-100 object-fit-cover" alt="Imagen 3" />
            </SplideSlide>
        </Splide>
    </div>
</div>
</template>


<script>
import { Splide, SplideSlide } from "@splidejs/vue-splide";
import "@splidejs/splide/dist/css/splide.min.css";

export default {
    name: "MiddleSection",
    components: {
        Splide,
        SplideSlide,
    },
    data() {
        return {
            splideOptions: {
                type: "loop",
                autoplay: true,
                interval: 5000,
                height: "100%",
                arrows: false,
                pagination: true,
            },
        };
    },
};
</script>

<style scoped>
.landing-section {
    height: 70vh;
    overflow: hidden;
}

.text-section {
    background: linear-gradient(to bottom right, #ff5328, #ffdd62);
    color: white;
    width: 35%;
    /* Ancho del texto */
    display: flex;
    justify-content: center;
    align-items: center;
    box-shadow: 0 0 15px 10px rgba(0, 0, 0, 0.5);
    z-index: 5;
}

.text-container{
    background: linear-gradient(to bottom right, #ffde65, #ff8363);
    color: white;
    height: 400px;
    width: 400px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 44px;
    font-family: 'Roboto', sans-serif;
    box-shadow: 20px 20px 0 5px rgba(255, 255, 255, 0.4);
}

.carousel-section {
    position: relative;
    width: 65%;
    z-index: 1;
}

.object-fit-cover {
    object-fit: cover;
}
</style>
